#!/usr/bin/env bash
# CodeIgniter 4 Domain Starter — environment initializer.
# Run from the project root after cloning.
# Usage: ./init.sh [--skip-deps] [--skip-db] [--skip-sync] [--skip-server]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/setup.sh
source "$SCRIPT_DIR/scripts/setup.sh"

SKIP_DEPS=false
SKIP_DB=false
SKIP_SYNC=false
SKIP_SERVER=false

while [ $# -gt 0 ]; do
  case $1 in
    --skip-deps)   SKIP_DEPS=true; shift ;;
    --skip-db)     SKIP_DB=true; shift ;;
    --skip-sync)   SKIP_SYNC=true; shift ;;
    --skip-server) SKIP_SERVER=true; shift ;;
    --help)
      printf "Usage: ./init.sh [OPTIONS]\n\n"
      printf "Options:\n"
      printf "  --skip-deps     Skip composer install\n"
      printf "  --skip-db       Skip database creation and migrations\n"
      printf "  --skip-sync     Skip permission sync against the hub\n"
      printf "  --skip-server   Do not offer to start the development server\n"
      printf "  --help          Show this help message\n"
      exit 0
      ;;
    *)
      print_error "Unknown option: $1"
      exit 1
      ;;
  esac
done

LOG_FILE="$(pwd)/init.log"
exec > >(tee -a "$LOG_FILE") 2>&1
printf "Init log: %s\n" "$LOG_FILE"

print_header "CI4 Domain Starter — Environment Setup"

# ---------------------------------------------------------------------------
# Requirements
# ---------------------------------------------------------------------------

print_header "Checking requirements"
require_cmd php
require_cmd composer
detect_mysql_mode

if ! php -r 'exit(version_compare(PHP_VERSION, "8.2.0", ">=") ? 0 : 1);'; then
  print_error "PHP 8.2+ is required (found: $(php -r 'echo PHP_VERSION;'))."
  exit 1
fi
print_ok "Dependencies found (php, composer)"

# ---------------------------------------------------------------------------
# Hub coordinates
# ---------------------------------------------------------------------------

print_header "Hub coordinates"
printf "This domain app delegates auth to a running ci4-api-starter (the hub).\n"
printf "You need: hub URL, an X-App-Key bound to a registered application,\n"
printf "and the application code.\n\n"

HUB_URL="$(ask_with_default 'Hub URL' 'http://localhost:8080')"
HUB_APP_CODE="$(ask_with_default 'Application code (registered in hub)' 'example-domain')"
read -r -p "X-App-Key: " HUB_API_KEY

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_USER="root"
DB_PASS=""
DB_NAME="ci4_domain"
TEST_DB_NAME="ci4_domain_test"

[ -n "$DETECTED_DOCKER_PORT" ] && DB_PORT="$DETECTED_DOCKER_PORT"

if [ "$SKIP_DB" = false ]; then
  print_header "Database configuration"
  DB_HOST="$(ask_with_default 'MySQL host' "$DB_HOST")"
  DB_PORT="$(ask_with_default 'MySQL port' "$DB_PORT")"
  DB_USER="$(ask_with_default 'MySQL user' "$DB_USER")"
  read -r -s -p "MySQL password (can be empty): " DB_PASS
  printf "\n"
  DB_NAME="$(ask_with_default 'Database name' "$DB_NAME")"
  TEST_DB_NAME="$(ask_with_default 'Test database name' "$TEST_DB_NAME")"
fi

# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

if [ "$SKIP_DEPS" = false ]; then
  print_header "Installing dependencies"
  composer install --no-interaction --no-progress
fi

print_header "Writing .env"
if [ -f ".env" ]; then
  print_warn ".env exists. Backing up to .env.bak.$(date +%s)"
  cp .env ".env.bak.$(date +%s)"
fi

cp .env.example .env
{
  printf '\n# --- Generated by init.sh ---\n'
  printf 'database.default.hostname = %s\n' "$DB_HOST"
  printf 'database.default.port = %s\n'     "$DB_PORT"
  printf 'database.default.username = %s\n' "$DB_USER"
  printf 'database.default.password = %s\n' "$DB_PASS"
  printf 'database.default.database = %s\n' "$DB_NAME"
  printf 'database.tests.database = %s\n'   "$TEST_DB_NAME"
  printf 'hub.url = %s\n'                   "$HUB_URL"
  printf 'hub.appCode = %s\n'               "$HUB_APP_CODE"
  printf 'hub.apiKey = %s\n'                "$HUB_API_KEY"
} >> .env

print_ok ".env written"

if [ "$SKIP_DB" = false ]; then
  print_header "Preparing database"
  php spark db:create "$DB_NAME" || print_warn "Could not create database (may already exist)."
  php spark db:create "$TEST_DB_NAME" || true
  php spark migrate
  print_ok "Migrations applied"
fi

# ---------------------------------------------------------------------------
# Sync permissions to hub
# ---------------------------------------------------------------------------

if [ "$SKIP_SYNC" = false ]; then
  print_header "Registering permissions in the hub"
  printf "domain:sync-permissions registers this app's permissions in the hub.\n"
  printf "It needs a superadmin JWT (one-time setup — service tokens lack iam.superadmin-access).\n"
  printf "Obtain one via: curl -X POST %s/api/v1/auth/login \\\n" "$HUB_URL"
  printf '    -H "Content-Type: application/json" -d '"'"'{"email":"...","password":"..."}'"'"'\n\n'
  read -r -p "Paste superadmin JWT (or press Enter to skip): " ADMIN_TOKEN

  if [ -n "$ADMIN_TOKEN" ]; then
    if php spark domain:sync-permissions --admin-token="$ADMIN_TOKEN"; then
      print_ok "Permissions synced"
    else
      print_warn "Permission sync failed — re-run later with:"
      printf "  php spark domain:sync-permissions --admin-token=<jwt>\n"
    fi
  else
    print_warn "Skipped. Run later with:"
    printf "  php spark domain:sync-permissions --admin-token=<jwt>\n"
  fi
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

print_header "Done"
printf "Domain app ready at: %s\n" "$(pwd)"
printf "Hub: %s (app=%s)\n" "$HUB_URL" "$HUB_APP_CODE"

if [ "$SKIP_SERVER" = false ]; then
  read -r -p "Start development server now? (y/N): " START_SERVER
  case "$(echo "$START_SERVER" | tr '[:upper:]' '[:lower:]')" in
    y|yes)
      print_header "Starting development server"
      printf "Server at http://localhost:8090 — press Ctrl+C to stop.\n\n"
      php spark serve --port 8090
      ;;
    *)
      printf "Start server: php spark serve --port 8090\n"
      ;;
  esac
fi
